pipeline {
    agent any

    environment {
        DOCKERHUB_CREDS = credentials('travissscottt-dockerhub')
    }

    options {
        timestamps()
        skipDefaultCheckout(true)
    }

    stages {
        stage('Clone GitHub Repository') {
            steps {
                cleanWs()
                sh 'git clone -b master https://github.com/Dolmachi/CI-CD-pipeline-Lab-1.git'
            }
        }

        stage('Checkout Repo Dir') {
            steps {
                dir('CI-CD-pipeline-Lab-1') {
                    sh 'ls -la'
                }
            }
        }
        
        stage('Download Data and Run Unit Tests') {
            steps {
                dir('CI-CD-pipeline-Lab-1') {
                    sh '''
                        bash -c "python3 -m venv venv && . venv/bin/activate && pip install -r requirements.txt && dvc pull && pytest src/unit_tests --cov=src"
                    '''
                }
            }
        }
        
        stage('Login to DockerHub') {
            steps {
                sh 'docker login -u $DOCKERHUB_CREDS_USR -p $DOCKERHUB_CREDS_PSW'
            }
        }
        
        stage('Build and Run Docker Container') {
            steps {
                dir('CI-CD-pipeline-Lab-1') {
                    sh 'bash -c "docker compose up -d"'
                }
            }
        }
        
        stage('Check Container Logs') {
            steps {
                dir("CI-CD-pipeline-Lab-1") {
                    sh '''
                        bash -c 'container_id=$(docker ps -qf "name=api_container"); if [ -z "$container_id" ]; then echo "No container running"; exit 1; fi; docker logs --tail 1000 "$container_id"'
                    '''
                }
            }
        }
        
        stage('Push Docker Image to DockerHub') {
            steps {
                sh '''
                    bash -c 'image_id=$(docker images -q api-image-1:latest); if [ -z "$image_id" ]; then echo "Error: Docker image not found. Build might have failed."; exit 1; fi; docker push api-image-1:latest'
                '''
            }
        }
    }

    post {
        always {
            sh '''
                bash -c "docker stop api-container || true; docker rm api-container || true; docker rmi api-image-1:latest || true; docker logout || true"
            '''
            cleanWs()
        }
    }
}
